 version: '3'
    
  services:
    db:
      image: kartoza/postgis
      env_file: 
        - ./docker-env/prod.env
    web:
      build:
        context: .
        dockerfile: ./dockerfile/Dockerfile
      command: 
        - ./execute-docker-prod.sh
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db
      restart: always