version: '3'
    
services:
  db:
    image: kartoza/postgis
    env_file: 
      - ./docker-env/dev.env
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: ./services/Dockerfile
    env_file: 
      - ./docker-env/dev.env
    command: 
      - ./execute-docker-dev.sh
    expose: 
      - 8080
    depends_on:
      - db
    restart: always
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 3000:80
    depends_on:
      - web