# Generated by Django 3.0.8 on 2020-07-25 18:00

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, unique=True, verbose_name='Description')),
                ('loc_geo', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geographic Localization')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('states', models.CharField(choices=[('TV', 'To Validate'), ('VT', 'Validated'), ('RV', 'Resolved')], default='TV', max_length=2, verbose_name='States')),
                ('category', models.CharField(choices=[('CN', 'Consruction'), ('SE', 'Special Event'), ('IC', 'Incident'), ('WC', 'Weather Condition'), ('RC', 'Road Condition')], default='CN', max_length=2, verbose_name='Category')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
