# Generated by Django 3.0.8 on 2020-07-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('CN', 'Construction'), ('SE', 'Special Event'), ('IC', 'Incident'), ('WC', 'Weather Condition'), ('RC', 'Road Condition')], default='CN', max_length=2, verbose_name='Category'),
        ),
    ]
